version: '3.8'
services:
  api:
    build: ./app
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./app/node_modules
  reservation:
    build: ./reservation
    container_name: reservation_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
